sudo: required
dist: trusty
language: python
notifications:
  email: false
cache:
  directories:
    - "$HOME/.cache/pip"
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install python-dev python-opencv -y
  - pip install -r requirements.txt
  - pip install coverage
script: "python -c 'import cv2' && ./run-tests.sh"
