language: python
notifications:
  email: false
python:
  - "2.7"
before_install:
 - sudo apt-get update
 - sudo apt-get install python-opencv
 - sudo dpkg -L python-opencv
install: "pip install -r requirements.txt && pip install coverage"
script: "./run-tests.sh"
